services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER:     __USER__
      POSTGRES_PASSWORD: __PASSWORD__
      POSTGRES_DB:       __DBNAME__
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL:      postgresql://__USER__:__PASSWORD__@db:5432/__DBNAME__
      FLASK_APP:         run.py
      FLASK_ENV:         development

      SECRET_KEY:        a_very_secret_key
      AUTH0_DOMAIN:      your-domain.auth0.com
      AUTH0_CLIENT_ID:   your_client_id
      AUTH0_CLIENT_SECRET:  your_client_secret
    ports:
      - "80:5000"
    volumes:
      - ./:/usr/src/app
      - ./app/uploads:/usr/src/app/app/uploads
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "run:app", "--workers", "2", "--threads", "4"]
    working_dir: /usr/src/app

volumes:
  db_data: