"""Add behavior table

Revision ID: 742784e08d20
Revises: 82c20affd4f2
Create Date: 2025-09-19 05:14:13.307697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742784e08d20'
down_revision = '82c20affd4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('behavior_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behaviors')
    # ### end Alembic commands ###
