"""Initial database setup

Revision ID: 82c20affd4f2
Revises: 
Create Date: 2025-09-15 04:27:13.590282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82c20affd4f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_start_utc', sa.DateTime(), nullable=False),
    sa.Column('timestamp_end_utc', sa.DateTime(), nullable=False),
    sa.Column('video_duration_seconds', sa.Float(), nullable=False),
    sa.Column('primary_species', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remote_video_path', sa.String(length=256), nullable=True),
    sa.Column('remote_json_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('detection_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classes_detected', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('classes_modified', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('max_count_per_frame', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('events')
    # ### end Alembic commands ###
